name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  
  workflow_dispatch:

  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Generate the snake game animation
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            outputs: |
            dist/github-snake.svg?color_snake=#64a1f4,#4b91f1,#3c7dd9,#8dbdff,#bfd6f6
            dist/github-snake-dark.svg?color_snake=#64a1f4,#4b91f1,#3c7dd9,#8dbdff,#bfd6f6
          
      # Push the generated files to the output branch
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
